import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Document } from 'react-pdf';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lucy de Rojas - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/media/logos/q.ico" />
      </Head>


      <h1>Lucy de Rojas Portfolio</h1>




      
      <iframe src="https://onedrive.live.com/embed?resid=EC6BF2592866F3BD%21133&amp;authkey=%21AB0z1gC--kIE3K4&amp;em=2&amp;wdAr=1.7777777777777777&amp;Embed=1&amp;wdEaa=1" width="100%" height="auto" frameBorder="1">This is an embedded <a href="https://office.com">Microsoft Office</a> presentation, powered by <a href="https://office.com/webapps">Office</a>.</iframe>




     
    </div>
  )
}
